import localFont from "next/font/local";
import { GoogleOAuthProvider } from "@react-oauth/google"; // Import the provider
import ContextProvider from "../components/context/ContextProvider";

import "./globals.css";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GoogleOAuthProvider clientId="1092218225335-pqgvqe84h71ouchupeotc247auh6nvje.apps.googleusercontent.com">
          <ContextProvider>

           {/* Render the page content (children) */}
            {children}
   
          </ContextProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
